name: wiredbrain
description: Project by majid Hajian

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  font_awesome_flutter: ^9.0.0-nullsafety
  google_fonts: ^2.0.0
  http: ^0.13.0
  firebase_core: '^1.0.0'
  firebase_analytics: '^7.1.1'

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
# run flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'
